### ISSUE TITLE
Set preset volume on start

### ISSUE THREAD

**Issue by jazzchng** [1umutda/MusicBot#3]
Hi there,

Awesome work btw and thank you for sharing this!
I would like to set a pre-set volume when the bot starts.
Can you guide me on what line can I add to main.js or config.js for this?

Thank you!!

**Comment by baechooYT** [comment]
Hello!

You can change pre-set volume with simple easy steps!

Goto commands -> music -> play.js and click Edit button(on github you can edit on your computer/server)
and after this line:
```js
res.playlist ? queue.addTracks(res.tracks) : queue.addTrack(res.tracks[0]);
```
add this:
```js
queue.setVolume(35);
```

**Comment by jazzchng** [comment]
Awesome! Thank you so much for helping me out! Thank you for sharing your awesome creation too this is a life saver! Quality is so much better too especially when playing music from a locally hosted server :D
